Updated the changes.
MadaZZ/JS-Concepts pull request #28
Opened 2020-09-30 10:11 UTC by ritikrana4

hey @MadaZZ , 
I have corrected what you asked for. Please see if any other changes are required.

2020-09-30 13:36 UTC, MadaZZ commented on 1 Foundations/this.js
> -// 'this' is an object that the function is a property of.
This definition should have been let be. This is something very short and explains a lot.

2020-09-30 13:41 UTC, MadaZZ requested changes

2020-09-30 13:41 UTC, MadaZZ commented on 1 Foundations/this.js
> +    alert(`Hello ${this.name} `);
Replace the alert with logs. 
That way, the code works properly in `repl.it` and also using node via terminal.

2020-10-01 09:37 UTC, MadaZZ approved these changes
Looks good

2020-10-01 09:37 UTC, merged

2020-10-01 11:02 UTC, ritikrana4 commented
@MadaZZ  great 👍