updated isArray()
MadaZZ/JS-Concepts pull request #52
Opened 2020-10-05 14:47 UTC by saurabhkanswal

i have added some more information with extra resource link.

2020-10-05 14:51 UTC, saurabhkanswal commented
why PR is showing not eligible in hacktoberfest dashboard.

2020-10-05 16:10 UTC, MadaZZ requested changes
Please change the format as requested. :)

2020-10-05 16:10 UTC, MadaZZ commented on 1 Foundations/isArray.js
> +// Return value: true if given parameter is an array otherwise it return false
The explanations look good! 👍🏻
Please look into [SampleJS.md](https://github.com/MadaZZ/JS-Concepts/blob/master/SampleJS.md) for file format

2020-10-11 10:11 UTC, MadaZZ reviewed
This can be written as a part of some other file. It is not something that needs a standalone program.

2020-10-11 10:11 UTC, MadaZZ commented on 1 Foundations/isArray.js
> +
Do not think this needs a standalone file!

2020-10-11 10:11 UTC, closed without merging